[package]
name = "ferrisdb-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ferrisdb-core = { path = "../ferrisdb-core" }
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"
tonic = "0.12"
prost = "0.13"
log = "0.4"